# Generated by Django 4.1.7 for Israel Amat Gil

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('promoted_teams', models.IntegerField(default=1)),
                ('relegated_teams', models.IntegerField(default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_day', models.IntegerField()),
                ('home_team_result', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('away_team_result', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=20)),
                ('goals', models.IntegerField(default=0)),
                ('asists', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('shorthand', models.CharField(max_length=3)),
                ('points', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('goals_lost', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.league')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('score_id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerid', to='main.player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamid', to='main.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayteam', to='main.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometeam', to='main.team'),
        ),
    ]
